config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  resource :rate, only: :show

  root to: 'rate#show'

  namespace 'admin' do
    resource :fixed_rate, except: [:edit, :destroy]

    root to: 'fixed_rates#show'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fixed_rate.rb
class FixedRate < ApplicationRecord
  validates :value, presence: true,
                    numericality: { greater_than: 0, less_than: 1000, allow_blank: true },
                    format: {
                      with: /\A\d+(?:\.\d{0,4})?\z/,
                      message: 'could have only 4 decimals',
                      allow_blank: true
                    }

  validates :unfix_at, presence: true

  def active?
    unfix_at > Time.zone.now
  end
end

app/controllers/admin/fixed_rates_controller.rb
class Admin::FixedRatesController < ApplicationController
  before_action :find_fixed_rate

  def create
    @fixed_rate = FixedRate.new(fixed_rate_params)

    if @fixed_rate.save
      RateService.new.broadcast_rate
      BroadcastRateJob.set(wait_until: FixedRate.first.unfix_at + 2.seconds).perform_later

      flash[:notice] = 'Success'
      redirect_to %i[admin fixed_rate]
    else
      flash[:notice] = 'An error was occurred'
      render 'show'
    end
  end

  def update
    if @fixed_rate.update(fixed_rate_params)
      RateService.new.broadcast_rate
      BroadcastRateJob.set(wait_until: FixedRate.first.unfix_at + 2.seconds).perform_later

      flash[:notice] = 'Success'
      redirect_to %i[admin fixed_rate]
    else
      flash[:notice] = 'An error was occurred'
      render 'show'
    end
  end

  def show; end

  private

  def fixed_rate_params
    params.require(:fixed_rate)
          .permit(:value, :unfix_at)
  end

  def find_fixed_rate
    @fixed_rate = FixedRate.first || FixedRate.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rate_controller.rb
class RateController < ApplicationController
  def show
    @rate = RateService.new.current_rate
  end
end

app/helpers/admin/fixed_rate_helper.rb
module Admin::FixedRateHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/fixed_rates/show.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <h1>Fixed currency rate</h1>

    <div class='well'>
      Current fixed curreny rate is <%= @fixed_rate.value %>, valid until <%= @fixed_rate.unfix_at %>
    </div>

    <div class='well'>
      <%= simple_form_for [:admin, @fixed_rate], url: admin_fixed_rate_path do |f| %>
        <%= f.input :value %>
        <%= f.input :unfix_at %>

        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FunBoxTestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container-fluid'>
      <div class='container'>
        <% if flash[:notice].present? %>
          <div class='alert alert-success alert-dismissible' role='alert'>
            <%= flash[:notice] %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/rate/_rate.html.erb
<span class='js-rates-channel'>
  <%= rate %>
</span>

app/views/rate/show.html.erb
<div class='row'>
  <div class='col-xs-12'>
    <h1>Currency rate</h1>

    <div class='well'>
      Current rate is <b><%= render partial: 'rate', locals: { rate: @rate } %></b>
    </div>
  </div>
</div>